
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__sample_adaptor_h__ADAPTOR_MARSHAL_H
#define __dbusxx__sample_adaptor_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace com {
namespace example {

class SampleInterface_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    SampleInterface_adaptor()
    : ::DBus::InterfaceAdaptor("com.example.SampleInterface")
    {
        bind_property(Bar, "y", true, true);
        register_method(SampleInterface_adaptor, Frobate, _Frobate_stub);
        register_method(SampleInterface_adaptor, Bazify, _Bazify_stub);
        register_method(SampleInterface_adaptor, Mogrify, _Mogrify_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument Frobate_args[] = 
        {
            { "foo", "i", true },
            { "bar", "s", false },
            { "baz", "a{us}", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument Bazify_args[] = 
        {
            { "bar", "(iiu)", true },
            { "bar", "v", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument Mogrify_args[] = 
        {
            { "bar", "(iiav)", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument Changed_args[] = 
        {
            { "new_value", "b", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod SampleInterface_adaptor_methods[] = 
        {
            { "Frobate", Frobate_args },
            { "Bazify", Bazify_args },
            { "Mogrify", Mogrify_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod SampleInterface_adaptor_signals[] = 
        {
            { "Changed", Changed_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty SampleInterface_adaptor_properties[] = 
        {
            { "Bar", "y", true, true },
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface SampleInterface_adaptor_interface = 
        {
            "com.example.SampleInterface",
            SampleInterface_adaptor_methods,
            SampleInterface_adaptor_signals,
            SampleInterface_adaptor_properties
        };
        return &SampleInterface_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */
    ::DBus::PropertyAdaptor< uint8_t > Bar;

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual void Frobate(const int32_t& foo, std::string& bar, std::map< uint32_t, std::string >& baz) = 0;
    virtual ::DBus::Variant Bazify(const ::DBus::Struct< int32_t, int32_t, uint32_t >& bar) = 0;
    virtual void Mogrify(const ::DBus::Struct< int32_t, int32_t, std::vector< ::DBus::Variant > >& bar) = 0;

public:

    /* signal emitters for this interface
     */
    void Changed(const bool& arg1)
    {
        ::DBus::SignalMessage sig("Changed");
        ::DBus::MessageIter wi = sig.writer();
        wi << arg1;
        emit_signal(sig);
    }

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Frobate_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        int32_t argin1; ri >> argin1;
        std::string argout1;
        std::map< uint32_t, std::string > argout2;
        Frobate(argin1, argout1, argout2);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        wi << argout2;
        return reply;
    }
    ::DBus::Message _Bazify_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Struct< int32_t, int32_t, uint32_t > argin1; ri >> argin1;
        ::DBus::Variant argout1 = Bazify(argin1);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _Mogrify_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Struct< int32_t, int32_t, std::vector< ::DBus::Variant > > argin1; ri >> argin1;
        Mogrify(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

} } 
#endif //__dbusxx__sample_adaptor_h__ADAPTOR_MARSHAL_H
